# Generated by Django 6.0.1 on 2026-04-23 06:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('veneus', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_date', models.DateTimeField(blank=True, null=True)),
                ('Umpire1', models.CharField(blank=True, max_length=30, null=True)),
                ('Umpire2', models.CharField(blank=True, max_length=30, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('upcoming', 'Upcoming'), ('completed', 'Completed'), ('live', 'Live')], default='pending', max_length=20)),
                ('result', models.CharField(choices=[('team1', 'Team1'), ('team2', 'Team2'), ('draw', 'Draw'), ('pending', 'Pending')], default='pending', max_length=20)),
                ('team1_runs', models.IntegerField(default=0)),
                ('team1_balls', models.IntegerField(default=0)),
                ('team2_runs', models.IntegerField(default=0)),
                ('team2_balls', models.IntegerField(default=0)),
                ('is_locked', models.BooleanField(default=False)),
                ('points_updated', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('team1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team1_matches', to='core.team')),
                ('team2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team2_matches', to='core.team')),
                ('venue', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='veneus.venue')),
            ],
        ),
        migrations.CreateModel(
            name='MatchPlayingXI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='matches.match')),
                ('team1_captain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team1_captain', to='core.player')),
                ('team1_players', models.ManyToManyField(related_name='team1_players', to='core.player')),
                ('team2_captain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team2_captain', to='core.player')),
                ('team2_players', models.ManyToManyField(related_name='team2_players', to='core.player')),
            ],
        ),
        migrations.CreateModel(
            name='PlayerStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_name', models.CharField(max_length=100)),
                ('team_name', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=20)),
                ('matches', models.IntegerField(default=0)),
                ('total_runs', models.IntegerField(default=0)),
                ('balls_faced', models.IntegerField(default=0)),
                ('wickets', models.IntegerField(default=0)),
                ('overs_bowled', models.FloatField(default=0)),
                ('runs_conceded', models.IntegerField(default=0)),
                ('strike_rate', models.FloatField(default=0)),
                ('economy', models.FloatField(default=0)),
                ('player', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.player')),
            ],
        ),
        migrations.CreateModel(
            name='PointsTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matches_played', models.IntegerField(default=0)),
                ('wins', models.IntegerField(default=0)),
                ('losses', models.IntegerField(default=0)),
                ('net_run_rate', models.FloatField(default=0.0)),
                ('points', models.IntegerField(default=0)),
                ('runs_scored', models.IntegerField(default=0)),
                ('balls_faced', models.IntegerField(default=0)),
                ('runs_conceded', models.IntegerField(default=0)),
                ('balls_bowled', models.IntegerField(default=0)),
                ('team', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.team')),
            ],
        ),
        migrations.CreateModel(
            name='PlayingXI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('captain', models.CharField(max_length=30)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matches.match')),
                ('players', models.ManyToManyField(to='core.player')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.team')),
            ],
            options={
                'unique_together': {('match', 'team')},
            },
        ),
    ]
