# Generated by Django 6.0.1 on 2026-04-23 06:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_name', models.CharField(max_length=100)),
                ('age', models.IntegerField(default=25)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('mobile', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('role', models.CharField(choices=[('Bowling', 'bowling'), ('Batting', 'batting'), ('AllRounder', 'allrounder')], default='Batting', max_length=20)),
                ('Batting_Style', models.CharField(choices=[('RIGHT_HAND_BATTER', 'right_hand_batter'), ('LEFT_HAND_BATTER', 'left_hand_batter')], default='RIGHT_HAND_BATTER', max_length=20)),
                ('Bowling_style', models.CharField(choices=[('RIGHT_ARM_FAST', 'right_arm_fast'), ('LEFT_ARM_FAST', 'left_arm_fast'), ('RIGHT_ARM_SPIN', 'right_arm_spin'), ('LEFT_ARM_SPIN', 'left_arm_spin')], default='RIGHT_ARM_FAST', max_length=20)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='player_photo/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=100)),
                ('short_name', models.CharField(default=False, max_length=5)),
                ('home_city', models.CharField(default=False, max_length=20)),
                ('head_coach', models.CharField(default=False, max_length=30)),
                ('home_ground', models.CharField(default=False, max_length=40)),
                ('primary_color', models.CharField(default=False, max_length=50)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='teams_logo/')),
                ('is_approved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('captain', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='captain_of', to='core.player')),
                ('franchise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.franchise')),
            ],
        ),
        migrations.AddField(
            model_name='player',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.team'),
        ),
    ]
